//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAppMain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string btnMore {
            get {
                return ResourceManager.GetString("btnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string btnSubscribe {
            get {
                return ResourceManager.GetString("btnSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string forget_password {
            get {
                return ResourceManager.GetString("forget_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Topics.
        /// </summary>
        public static string hdHotTopics {
            get {
                return ResourceManager.GetString("hdHotTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Update.
        /// </summary>
        public static string hdRecentUpdate {
            get {
                return ResourceManager.GetString("hdRecentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe our email list.
        /// </summary>
        public static string lblSubscribe {
            get {
                return ResourceManager.GetString("lblSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least 6 characters long..
        /// </summary>
        public static string Must_be_at_least_6_char {
            get {
                return ResourceManager.GetString("Must_be_at_least_6_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string navAboutUs {
            get {
                return ResourceManager.GetString("navAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string navActivities {
            get {
                return ResourceManager.GetString("navActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string navCalendar {
            get {
                return ResourceManager.GetString("navCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string navClasses {
            get {
                return ResourceManager.GetString("navClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Intro.
        /// </summary>
        public static string navClassIntro {
            get {
                return ResourceManager.GetString("navClassIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string navClub {
            get {
                return ResourceManager.GetString("navClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events / Clubs.
        /// </summary>
        public static string navCommunity {
            get {
                return ResourceManager.GetString("navCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string navContactUs {
            get {
                return ResourceManager.GetString("navContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum.
        /// </summary>
        public static string navCurriculum {
            get {
                return ResourceManager.GetString("navCurriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string navForms {
            get {
                return ResourceManager.GetString("navForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string navHome {
            get {
                return ResourceManager.GetString("navHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string navLogin {
            get {
                return ResourceManager.GetString("navLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string navLogoff {
            get {
                return ResourceManager.GetString("navLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string navMyAcct {
            get {
                return ResourceManager.GetString("navMyAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string navRegister {
            get {
                return ResourceManager.GetString("navRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string navRules {
            get {
                return ResourceManager.GetString("navRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Activities.
        /// </summary>
        public static string navSchoolActivities {
            get {
                return ResourceManager.GetString("navSchoolActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Info.
        /// </summary>
        public static string navSchoolInfo {
            get {
                return ResourceManager.GetString("navSchoolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About HCCS.
        /// </summary>
        public static string navSchoolIntro {
            get {
                return ResourceManager.GetString("navSchoolIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Team.
        /// </summary>
        public static string navSchoolTeam {
            get {
                return ResourceManager.GetString("navSchoolTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string Password_must_match {
            get {
                return ResourceManager.GetString("Password_must_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new family.
        /// </summary>
        public static string reg_as_a_new_user {
            get {
                return ResourceManager.GetString("reg_as_a_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Year.
        /// </summary>
        public static string schoolyear {
            get {
                return ResourceManager.GetString("schoolyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Howard County Chinese School.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string thCampus {
            get {
                return ResourceManager.GetString("thCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Capacity.
        /// </summary>
        public static string thClassCapacity {
            get {
                return ResourceManager.GetString("thClassCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string thClassName {
            get {
                return ResourceManager.GetString("thClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string thClassroom {
            get {
                return ResourceManager.GetString("thClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Time.
        /// </summary>
        public static string thClassTime {
            get {
                return ResourceManager.GetString("thClassTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string thDate {
            get {
                return ResourceManager.GetString("thDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Age.
        /// </summary>
        public static string thMinimumAge {
            get {
                return ResourceManager.GetString("thMinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string thNotes {
            get {
                return ResourceManager.GetString("thNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Fee.
        /// </summary>
        public static string thRegistrationFee {
            get {
                return ResourceManager.GetString("thRegistrationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string thTeacher {
            get {
                return ResourceManager.GetString("thTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbook.
        /// </summary>
        public static string thTextbook {
            get {
                return ResourceManager.GetString("thTextbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbook Fee.
        /// </summary>
        public static string thTextbookFee {
            get {
                return ResourceManager.GetString("thTextbookFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuition.
        /// </summary>
        public static string thTuition {
            get {
                return ResourceManager.GetString("thTuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string thWeek {
            get {
                return ResourceManager.GetString("thWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your HCCS account to log in.
        /// </summary>
        public static string txtLoginPrompt {
            get {
                return ResourceManager.GetString("txtLoginPrompt", resourceCulture);
            }
        }
    }
}
